easy_admin:
    site_name: 'Deiak'
    design:
        form_theme:   'vertical'
        color_scheme: 'dark'
        assets:
            css:
                - '/bundles/app/css/estiloa.css'
                - '/bundles/app/css/skin-blue.css'
#            js:
#                - '/bundles/app/js/maplace.min.js'
