<?php

namespace AppBundle\Repository;

/**
 * DeiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeiaRepository extends \Doctrine\ORM\EntityRepository
{
}
