<?php

namespace AppBundle\Repository;

/**
 * FitxatuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitxatuRepository extends \Doctrine\ORM\EntityRepository
{
}
