<?php

namespace AppBundle\Repository;

/**
 * TeknikoaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeknikoaRepository extends \Doctrine\ORM\EntityRepository
{
}
