app:
    resource: "@AppBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /kudeatu

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

acme_api_demos:
  type: rest
  resource: AppBundle\Controller\ApiController
  prefix: /api
  options:
          expose: true

