security:

    providers:
        user_db:
            entity: { class: AppBundle\Entity\Teknikoa, property: username }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: user_db
#                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
#                csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/kudeatu/, role: ROLE_ADMIN }
#security:
##
##    role_hierarchy:
##        ROLE_ADMIN: [ROLE_USER]
##
#    providers:
#        user_db:
#            entity: { class: AppBundle\Entity\Teknikoa, property: username }
##
##    firewalls:
##        main:
##            pattern:    ^/
##            provider: user_db
##            form_login:
##                login_path: teknikoa_login
##                check_path: teknikoa_dologin
##                remember_me: true
##
##            security: true
##            anonymous: true
##    access_control:
##        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
##        - { path: /deiak, roles: ROLE_USER }
##        - { path: ^/admin/, role: ROLE_ADMIN }
