security:
    providers:
        main:
            entity: { class: AppBundle\Entity\Teknikoa, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
#            form_login:
#                login_path:  /teknikoa/login
#                check_path:  /teknikoa/dologin

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/teknikoa/dologin , roles: IS_AUTHENTICATED_ANONYMOUSLY}