security:

    providers:
        user_db:
            entity: { class: AppBundle\Entity\Teknikoa, property: username }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: user_db
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/kudeatu/, role: ROLE_ADMIN }
        - { path: ^/deia/, role: ROLE_ADMIN }