easy_admin:
    entities:
        Category:
            class: AppBundle\Entity\Category
            label: 'Kategoria'
            list:
                title: '%%entity_label%%k'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields: ['id','name','parent','children']

            show:
                fields: ['name','parent','children']

            form:
                fields:
                    - { property: 'name', label: 'Izena'  }
                    - { property: 'parent', label: 'Kategoria' , type_options: { placeholder: 'Aukeratu Kategoria nagusia...' } }
                    - { property: 'children', label: 'Azpi Kategoria' }